### DISCUSSION TITLE
UVDAR measurements affected by high error

### DISCUSSION THREAD

**Discussion by Kaktusowy500** [ctu-mrs/uvdar_core#8] [Q&A] [answered]
Hello,
When I was testing an UVDAR System in simualtion, I found a quite strange problem. Major and unexpected shift in measured position occurs when I change observer heading a bit and observed drone remains stationary. In some situations it works pretty well but in another the error is really high. During my investigation I found that this issue occurs when drones are in distance grater than 7-8 meters and it repeats about every 15 degrees change in heading. For test, I spawned two quadrocopters in 10m distance along x axis, on the same altitude and then I was changing heading of observer very slowly. Example situation:
![test_vizualization](https://user-images.githubusercontent.com/56251265/159545448-7352bb92-0897-46e3-87c7-3e9fdf6cbc29.png)

Changes in measured position on each axis, compared to ground truth are presented bellow:
![x_pos_when_rotating](https://user-images.githubusercontent.com/56251265/159543015-4d83793d-f85a-4227-bd3a-ef165aef8712.png)
I also prepared XY plot presenting a total error in position (euclidean distance between measured and ground truth position, in meters) in relation to observer heading(degrees). It was made when the position between drones was equal about 10 meters.
![10m_error_to_heading](https://user-images.githubusercontent.com/56251265/159544360-04ff4867-0c50-4629-85e2-3f8ee0c320d5.png)
Issue is rather not related to observer movement because it also occurs when observer remains stationary but has the specified affected heading. I have found that error is lower when the drone is visible on two camera (heading close to 0). Problem does not occur when observed drone is rotated in such a manner that its 3 LEDs are visible.

What could be causing this issue and is there any way to eliminate or mitigate it? Is it a known constraint of the system or maybe my configuration is incorrect?

Thanks a lot for your help!
Regards

## Detailed steps to reproduce

Start from working mrs system and freshly cloned uvdar_core package then add or modify following files of in uvdar_core package:

<details>
  <summary>Add tmux script to scripts directory:</summary>
`uvdar_single_uav.yml`:

```yaml
name: simulation
root: ./
startup_window: uv_observer 
pre_window: 'export RUN_TYPE=simulation; 
            export UAV_TYPE=f450; 
            export WORLD_NAME=simulation; 
            export ODOMETRY_TYPE=gps; 
            export SENSORS="garmin_down"
            export WORLD_FILE=$(rospack find uvdar_core)/scripts/custom_configs/world_simulation.yaml'
windows:
  - roscore:
      layout: even-vertical
      panes:
        - 'pkill px4;
          roscore'
  - gazebo:
      layout: even-vertical
      panes:
        - waitForRos; roslaunch uvdar_core uvdar_gazebo.launch gui:=true
  - status:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForRos; roslaunch mrs_uav_status status.launch
        - export UAV_NAME=uav2; waitForRos; roslaunch mrs_uav_status status.launch
  - spawn:
      layout: even-vertical
      panes:
        - waitForSimulation; rosservice call /mrs_drone_spawner/spawn  "1 $UAV_TYPE --pos-file $(rospack find uvdar_core)/scripts/positions.csv --enable-rangefinder --enable-ground-truth --enable-dual-uv-cameras --enable-back-uv-camera --uvcam_calib_file \"$(rospack find uvdar_core)/include/OCamCalib/config/calib_results_bf_uv_fe.txt\""
        - waitForSimulation; sleep 12; rosservice call /mrs_drone_spawner/spawn  "2 $UAV_TYPE --pos-file $(rospack find uvdar_core)/scripts/positions.csv --enable-rangefinder --enable-ground-truth --enable-uv-leds --uvled_s_l 0 --uvled_s_r 0"
  - control:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForOdometry; roslaunch mrs_uav_general core.launch config_mpc_tracker:=./custom_configs/mpc_tracker.yaml
        - export UAV_NAME=uav2; waitForOdometry; roslaunch mrs_uav_general core.launch config_mpc_tracker:=./custom_configs/mpc_tracker.yaml
  - autostart:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
  - takeoff:
      layout: even-vertical
      panes:
        - 'export UAV_NAME=uav1;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        - 'export UAV_NAME=uav2;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
  - rviz:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForControl; roslaunch uvdar_core multimodal_hypothesis_rviz.launch
  - uv_observer:
      layout: even-vertical
      panes:
        - waitForCompile; gz world --pause=0; sleep 6;  export UAV_NAME=uav1; waitForControl; roslaunch uvdar_core sim_three_sided.launch
  - kalman_filter:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav1; waitForControl; roslaunch uvdar_core uvdar_kalman_identified_3.launch output_frame:=$UAV_NAME/stable_origin

```

`uvdar_single_uav.sh`:

```bash
#!/bin/bash

if_is_link=`readlink $0`
command_name=$0
if [[ if_is_link ]]; then
  command_name=$if_is_link
fi

MY_PATH=`dirname "$if_is_link"`
MY_PATH=`( cd "$MY_PATH" && pwd )`
cd $MY_PATH

# remove the old link
rm .tmuxinator.yml

# link the session file to .tmuxinator.yml
ln uvdar_single_uav.yml .tmuxinator.yml

# start tmuxinator
tmuxinator
```
</details>

<details>
  <summary>Add positions.csv file to  scripts/custom_configs directory </summary>
```
1,0.0,0.0,2.0,0.0
2,10.0,0.0,2.0,0.0
```

</details>

<details>
  <summary>Add custom_config/world_simulation.yaml:</summary>

```yaml
#
## DEFINITION OF THE ARENA
#

utm_origin_units: 1 # 0 - UTM, 1 - Latitude Longitude
# !!! BEWARE !!!: the lat&lon and UTM coordinates below might be wrong
# !!! do NOT just switch utm_origin_units from 0<->1, the other form
# !!! might not be updated or even set correctly in the first place.
utm_origin_x: 465710.758973
utm_origin_y: 5249465.43086
utm_origin_lat: 47.397743
utm_origin_lon: 8.545594

init_gps_origin_local: false # origin of gps_origin will be in the position of UAV at odometry launch
init_gps_offset_x: 0.0 # initial position of UAV relative to gps_origin when init_gps_origin_local is enabled
init_gps_offset_y: 0.0 # initial position of UAV relative to gps_origin when init_gps_origin_local is enabled

safety_area:

  use_safety_area: false

  frame_name: "gps_origin"

  # convex polygon CCW
  safety_area: [-50, -50,
  50, -50,
  50, 50,
  -50, 50]

  polygon_obstacles:
    # loaded as a vector of matrices
    # each matrix has polygon vertices in columns
    # [[M1], [M2]]
    enabled: false
    data: [8.6, 18.61, 20.35, 6.82, -3.14, 10.7,
           -22.5, -22.71, 1.02, 17.68, 11.1, -4.1]
    rows: 2 # each matrix has two rows
    cols: [6] # nums of cols of each matrix

  point_obstacles:
    # loaded as a vector of matrices
    # x, y, radius
    enabled: false
    # [x1, y1, radisu1, height1,
    #  x2, y2, radius2, height2]
    data: [-5.0, -5.0, 2, 2,
           -10.0, -10.0, 4, 2]
    rows: 1 # each matrix has a single row
    cols: [4, 4] # nums of cols of each matrix

  max_height: 15.0
  min_height: 0.5
```

</details>

<details>
  <summary>replace mpc_tracker.yaml content with:</summary>

```yaml
version: "1.0.2.0"

mpc_rate: 100.0 # rate of MPC calculation, >= 10 Hz

diagnostics: # diagnostics publisher
  rate: 30                             # [Hz]
  position_tracking_threshold: 1.0     # [m] distance considered as "in place"
  orientation_tracking_threshold: 0.3  # [rad] orientation error considered as fine during tracking

braking:
  enabled: true # true
  q_vel_braking: 2000.0
  q_vel_no_braking: 0.0

wiggle:
  enabled: false
  amplitude: 0.5 # [m]
  frequency: 0.2 # [Hz]

# mrs collision avoidance
collision_avoidance:

  enabled: false # true
  trajectory_timeout: 1.0 # [s]
  radius: 0 # 3.0 # [m]
  inflation_radius: 0.6 # 1.0 # [m] if a collision is detected in (radius + inflation radius) the uav will start to slow down. Do not set this variable lower than 0.5
  altitude_threshold: 2.9 # [m]
  correction: 0.1 # 3.0 # [m]
  predicted_trajectory_publish_rate: 2 # [Hz]
  collision_horizontal_speed_coef: 0.15 # when collision detected, slow down during the manouver
  collision_slow_down_fully: 4 # 10 # when collision detected, slow down fully this number of steps before it
  collision_slow_down_start: 4 # 25 # when collision detected, start slowing down this number of steps before it
  collision_start_climbing: 4 # 25 # when avoiding, start climbing this number of steps before it

model:

  translation:

    n_states: 12
    n_inputs: 3

    A: [1, 0.01, 0.00005,       0, 0,   0,        0,       0, 0,    0,       0,       0,
        0,    1,    0.01, 0.00005, 0,   0,        0,       0, 0,    0,       0,       0,
        0,    0,       1,    0.01, 0,   0,        0,       0, 0,    0,       0,       0,
        0,    0,       0,       1, 0,   0,        0,       0, 0,    0,       0,       0,
        0,    0,       0,       0, 1, 0.01, 0.00005,       0, 0,    0,       0,       0,
        0,    0,       0,       0, 0,    1,    0.01, 0.00005, 0,    0,       0,       0,
        0,    0,       0,       0, 0,    0,       1,    0.01, 0,    0,       0,       0,
        0,    0,       0,       0, 0,    0,       0,       1, 0,    0,       0,       0,
        0,    0,       0,       0, 0,    0,       0,       0, 1, 0.01, 0.00005,       0,
        0,    0,       0,       0, 0,    0,       0,       0, 0,    1,    0.01, 0.00005,
        0,    0,       0,       0, 0,    0,       0,       0, 0,    0,       1,    0.01,
        0,    0,       0,       0, 0,    0,       0,       0, 0,    0,       0,       1]

    B: [0, 0, 0,
        0, 0, 0,
        0, 0, 0,
        0.01, 0, 0,
        0, 0, 0,
        0, 0, 0,
        0, 0, 0,
        0, 0.01, 0,
        0, 0, 0,
        0, 0, 0,
        0, 0, 0,
        0, 0, 0.01]

  heading:

    n_states: 4
    n_inputs: 1

    A: [1, 0.01, 0.00005,       0,
        0,    1,    0.01, 0.00005,
        0,    0,       1,    0.01,
        0,    0,       0,       1]

    B: [0,
        0,
        0,
        0.01]

mpc_solver:

  horizon_len: 40 # Horizon length is hardcoded in solver code, this value is used in other parts of the code

  # dt1: 0.01 # dt1 is set as 1/main_rate
  dt2: 0.2

  xy:
    verbose: false
    max_n_iterations: 25 # default: 25
    Q: [5000, 0, 0, 0]

  z:
    verbose: false
    max_n_iterations: 25 # default: 25
    Q: [5000, 0, 0, 0]

  heading:
    verbose: false
    max_n_iterations: 25 # default: 25
    Q: [5000, 0, 0, 0]

```
</details>

<details>
  <summary>Add turn_around_test.sh script which changes observer heading:</summary>

```bash
#! /bin/bash

while true
do 
    rosservice call uav1/control_manager/set_heading_relative "goal: 0.05"
    sleep 0.1
done

```

</details>

Run `./uvdar_single_uav.sh`

When drones had started and are hovering run  `./turn_around_test.sh`

Use Plotjuggler for visualization
